import type { Product } from './types';

export const CATEGORIES = [
  { id: 'all', name: 'All', emoji: '🛒' },
  { id: 'dairy', name: 'Dairy', emoji: '🥛' },
  { id: 'staples', name: 'Staples', emoji: '🌾' },
  { id: 'snacks', name: 'Snacks', emoji: '🍪' },
  { id: 'household', name: 'Household', emoji: '🧴' },
  { id: 'beverages', name: 'Beverages', emoji: '🥤' },
  { id: 'personal', name: 'Personal Care', emoji: '🧼' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Amul Taaza Toned Milk',
    brand: 'Amul',
    category: 'dairy',
    price: 27,
    mrp: 30,
    unit: '500 ml',
    barcode: '8901007007005',
    image: 'https://www.bbassets.com/media/uploads/p/l/40114416_8-amul-taaza-milk.jpg',
    description: 'Fresh toned milk pasteurised and homogenised. Rich in calcium and protein for a healthy start to your day.',
    stock: 48,
    rating: 4.6,
    reviews: 1284,
    offer: '10% off',
    tag: 'bestseller',
  },
  {
    id: 'p2',
    name: 'Fortune Sunlite Refined Oil',
    brand: 'Fortune',
    category: 'staples',
    price: 135,
    mrp: 165,
    unit: '1 L',
    barcode: '8901030865247',
    image: 'https://www.bbassets.com/media/uploads/p/l/274148_15-fortune-sun-lite-sunflower-refined-oil.jpg',
    description: 'Refined sunflower oil with the goodness of Vitamin A & D. Light and healthy for everyday cooking.',
    stock: 30,
    rating: 4.5,
    reviews: 892,
    offer: '18% off',
    tag: 'deal',
  },
  {
    id: 'p3',
    name: 'Aashirvaad Superior Atta',
    brand: 'Aashirvaad',
    category: 'staples',
    price: 290,
    mrp: 335,
    unit: '5 kg',
    barcode: '8901058852391',
    image: 'https://m.media-amazon.com/images/I/9104JpXbv6L._AC_UF894,1000_QL80_.jpg',
    description: '100% whole wheat atta, stone-ground for soft and fluffy rotis. Sourced from the finest wheat fields.',
    stock: 22,
    rating: 4.7,
    reviews: 2103,
    offer: '13% off',
    tag: 'bestseller',
  },
  {
    id: 'p4',
    name: 'Tata Salt Iodised',
    brand: 'Tata',
    category: 'staples',
    price: 28,
    mrp: 30,
    unit: '1 kg',
    barcode: '8901030657931',
    image: 'https://www.mystore.in/s/62ea2c599d1398fa16dbae0a/6538dce9137b08e081c8a576/tata-salt-800x800.PNG',
    description: 'Iodised salt for balanced taste and health. Vacuum-evaporated for purity and free-flowing texture.',
    stock: 60,
    rating: 4.8,
    reviews: 3420,
    offer: '7% off',
    tag: 'bestseller',
  },
  {
    id: 'p5',
    name: 'Maggi 2-Minute Masala Noodles',
    brand: 'Maggi',
    category: 'snacks',
    price: 56,
    mrp: 60,
    unit: '4 x 70 g',
    barcode: '8901058004015',
    image: 'https://m.media-amazon.com/images/I/719nAO+UEwL._SX679_.jpg',
    description: 'Instant noodles with the classic masala tastemaker. Ready in just 2 minutes for a quick meal.',
    stock: 75,
    rating: 4.5,
    reviews: 5621,
    offer: '7% off',
    tag: 'bestseller',
  },
  {
    id: 'p6',
    name: 'Parle-G Original Glucose Biscuits',
    brand: 'Parle',
    category: 'snacks',
    price: 45,
    mrp: 50,
    unit: '800 g',
    barcode: '8901719101090',
    image: 'https://m.media-amazon.com/images/I/714PuAiIeeL.jpg',
    description: 'The iconic glucose biscuits loved by generations. Crispy, light and full of wheat goodness.',
    stock: 90,
    rating: 4.7,
    reviews: 4302,
    offer: '10% off',
    tag: 'deal',
  },
  {
    id: 'p7',
    name: 'Surf Excel Easy Wash Detergent',
    brand: 'Surf Excel',
    category: 'household',
    price: 199,
    mrp: 230,
    unit: '2 kg',
    barcode: '8901030789123',
    image: 'https://m.media-amazon.com/images/I/619HRPW3elL._SL1000_.jpg',
    description: 'Powerful detergent powder that removes tough stains effortlessly. Suitable for machine and hand wash.',
    stock: 18,
    rating: 4.4,
    reviews: 712,
    offer: '13% off',
    tag: 'deal',
  },
  {
    id: 'p8',
    name: 'Britannia Brown Bread',
    brand: 'Britannia',
    category: 'snacks',
    price: 45,
    mrp: 50,
    unit: '400 g',
    barcode: '8901007001234',
    image: 'https://www.bbassets.com/media/uploads/p/l/40092241_8-britannia-brown-bread-with-goodness-of-wheat-enriched-with-vitamins.jpg',
    description: 'Soft brown bread baked with the goodness of wheat. Perfect for sandwiches and toast.',
    stock: 35,
    rating: 4.3,
    reviews: 540,
    offer: '10% off',
    tag: 'new',
  },
  {
    id: 'p9',
    name: 'Real Mixed Fruit Juice',
    brand: 'Real',
    category: 'beverages',
    price: 110,
    mrp: 120,
    unit: '1 L',
    barcode: '8901030456789',
    image: 'https://images.apollo247.in/pub/media/catalog/product/R/E/REA0064_1_1.jpg?tr=w-264,q-80,f-webp,dpr-3,c-at_max',
    description: 'Refreshing mixed fruit juice with no added preservatives. Packed with the goodness of real fruits.',
    stock: 28,
    rating: 4.2,
    reviews: 331,
    offer: '8% off',
  },
  {
    id: 'p10',
    name: 'Colgate Strong Teeth Toothpaste',
    brand: 'Colgate',
    category: 'personal',
    price: 89,
    mrp: 99,
    unit: '200 g',
    barcode: '8901314010012',
    image: 'https://m.media-amazon.com/images/I/419tA22Mk-L._SY300_SX300_QL70_FMwebp_.jpg',
    description: 'Toothpaste with calcium boost for stronger teeth. Protects against cavities and freshens breath.',
    stock: 52,
    rating: 4.6,
    reviews: 1840,
    offer: '10% off',
    tag: 'bestseller',
  },
  {
    id: 'p11',
    name: 'Amul Butter',
    brand: 'Amul',
    category: 'dairy',
    price: 56,
    mrp: 60,
    unit: '100 g',
    barcode: '8901007007056',
    image: 'https://images.pexels.com/photos/30660275/pexels-photo-30660275.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Pasteurised salted butter with a rich creamy taste. Perfect for spreading, cooking and baking.',
    stock: 40,
    rating: 4.8,
    reviews: 2980,
    offer: '7% off',
    tag: 'bestseller',
  },
  {
    id: 'p12',
    name: 'Tata Tea Gold',
    brand: 'Tata',
    category: 'beverages',
    price: 270,
    mrp: 300,
    unit: '500 g',
    barcode: '8901030657121',
    image: 'https://images.pexels.com/photos/667229/pexels-photo-667229.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Premium tea blend with long leaves and rich aroma. Brews a strong, refreshing cup every morning.',
    stock: 33,
    rating: 4.6,
    reviews: 1520,
    offer: '10% off',
  },
  {
    id: 'p13',
    name: 'Nescafé Classic Coffee',
    brand: 'Nescafé',
    category: 'beverages',
    price: 320,
    mrp: 360,
    unit: '100 g',
    barcode: '8901007054321',
    image: 'https://images.pexels.com/photos/162994/coffee-coffee-cup-cup-cafe-162994.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Instant coffee made from fine quality roasted beans. Rich aroma and smooth taste in every sip.',
    stock: 26,
    rating: 4.7,
    reviews: 980,
    offer: '11% off',
    tag: 'bestseller',
  },
  {
    id: 'p14',
    name: 'Coca-Cola Soft Drink',
    brand: 'Coca-Cola',
    category: 'beverages',
    price: 40,
    mrp: 45,
    unit: '750 ml',
    barcode: '8901007067890',
    image: 'https://images.pexels.com/photos/5869812/pexels-photo-5869812.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'The original refreshing cola taste. Best served chilled for those hot summer afternoons.',
    stock: 64,
    rating: 4.4,
    reviews: 2210,
    offer: '11% off',
  },
  {
    id: 'p15',
    name: "Lay's Classic Salted Chips",
    brand: "Lay's",
    category: 'snacks',
    price: 30,
    mrp: 35,
    unit: '52 g',
    barcode: '8901007078901',
    image: 'https://images.pexels.com/photos/6485538/pexels-photo-6485538.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Crispy potato chips with the perfect balance of salt. An irresistible snack for any time of day.',
    stock: 80,
    rating: 4.5,
    reviews: 1670,
    offer: '14% off',
    tag: 'deal',
  },
  {
    id: 'p16',
    name: 'Cadbury Dairy Milk Silk',
    brand: 'Cadbury',
    category: 'snacks',
    price: 95,
    mrp: 110,
    unit: '150 g',
    barcode: '8901007089012',
    image: 'https://images.pexels.com/photos/37857736/pexels-photo-37857736.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Smooth and silky milk chocolate that melts in your mouth. A perfect gift for every occasion.',
    stock: 45,
    rating: 4.8,
    reviews: 3120,
    offer: '14% off',
    tag: 'bestseller',
  },
  {
    id: 'p17',
    name: 'Vim Dishwash Liquid Gel',
    brand: 'Vim',
    category: 'household',
    price: 175,
    mrp: 199,
    unit: '750 ml',
    barcode: '8901030790123',
    image: 'https://images.pexels.com/photos/28921817/pexels-photo-28921817.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Powerful dishwash liquid gel that cuts through tough grease. Lemon fresh fragrance for sparkling clean dishes.',
    stock: 38,
    rating: 4.5,
    reviews: 620,
    offer: '12% off',
    tag: 'new',
  },
  {
    id: 'p18',
    name: 'Dettol Original Hand Wash',
    brand: 'Dettol',
    category: 'personal',
    price: 120,
    mrp: 140,
    unit: '200 ml',
    barcode: '8901030791230',
    image: 'https://images.pexels.com/photos/4328899/pexels-photo-4328899.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Trusted germ protection hand wash. Kills 99.9% of germs and leaves your hands soft and fresh.',
    stock: 50,
    rating: 4.6,
    reviews: 1140,
    offer: '14% off',
    tag: 'bestseller',
  },
  {
    id: 'p19',
    name: 'Pepsi Soft Drink',
    brand: 'Pepsi',
    category: 'beverages',
    price: 38,
    mrp: 42,
    unit: '750 ml',
    barcode: '8901007092345',
    image: 'https://images.pexels.com/photos/11942007/pexels-photo-11942007.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'The bold and refreshing cola taste of Pepsi. Best enjoyed chilled with friends and family.',
    stock: 58,
    rating: 4.3,
    reviews: 980,
    offer: '10% off',
  },
  {
    id: 'p20',
    name: 'Britannia Marie Gold Biscuits',
    brand: 'Britannia',
    category: 'snacks',
    price: 30,
    mrp: 35,
    unit: '250 g',
    barcode: '8901007005678',
    image: 'https://images.pexels.com/photos/38377151/pexels-photo-38377151.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Light and crispy tea-time biscuits. A wholesome snack made with the goodness of wheat.',
    stock: 70,
    rating: 4.4,
    reviews: 890,
    offer: '14% off',
    tag: 'deal',
  },
];

export const OFFERS = [
  {
    id: 'o1',
    title: 'Mega Saver Weekend',
    subtitle: 'Up to 25% off on staples',
    code: 'WEEKEND25',
    image: 'https://images.pexels.com/photos/11831458/pexels-photo-11831458.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    id: 'o2',
    title: 'Dairy Delight',
    subtitle: 'Buy 2 Amul products, get 10% off',
    code: 'DAIRY10',
    image: 'https://images.pexels.com/photos/18258533/pexels-photo-18258533.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    id: 'o3',
    title: 'Snack Attack',
    subtitle: 'Flat ₹50 off on snacks above ₹200',
    code: 'SNACK50',
    image: 'https://images.pexels.com/photos/21582447/pexels-photo-21582447.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
];

export const HERO_IMAGE =
  'https://images.pexels.com/photos/6753523/pexels-photo-6753523.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';

export const formatINR = (amount: number): string =>
  '₹' + amount.toLocaleString('en-IN', { minimumFractionDigits: 0, maximumFractionDigits: 2 });
